### ISSUE TITLE
Max rpm

### ISSUE THREAD

**Issue by calimero4** [JoachimF/JF-ECU32#1]
Hello Joachim,
Do you know how much revolutions per minute would be possible with you program?
I'm building and build so far 3 different turbines half the sice of a Lambert Kolibri and a turboprop attachment for those (140g and 1.2-1.3kg trust at 250.000 at "only" 520c, turboprop and turbine 380g) and would love to try 260.000/280.000rpm.

I've read the thread in the usinages forum and all I could find and if you still need translation to English or German I could do this!

Best regards
Matthias

**Comment by JoachimF** [comment]
Hello,

With the ESP32, max RPM should be over 500.000rpm

I will test with a fonction generator, I have only a Wren55.
Thanks for your help for the German language, you see that the last code is in the dev branch.
On january 2025, I will have more much time to work on the Ecu and finish a fully automatic version.
Have you tried to compile the code ?
I need to order the last pcb, because previous have bugs or missing functions.

Regards,

Joachim

**Comment by calimero4** [comment]
Hey,
Oh that sounds great!
I tried, but I'm only familiar with the arduino ide so it did not work and I'm still trying to figure out how to do this. Or is there maybe a good guideline somewhere for compiling and flashing I did not find jet?

I got all the hardware at home and would try this weekend to build onto a breadboard for testing.



Regards 
Matthias

**Comment by calimero4** [comment]
Here are the files for german end english!

[languages de and en.zip](https://github.com/user-attachments/files/17866832/languages.de.and.en.zip)

I need to order also some pcb´s from china or usa for me so i could add some of the ecu pcb´s also and send you those so it would be cheaper and only one time shipping to europe from the manufacturer. I could also reflow the smd components if that would help.

**Comment by calimero4** [comment]
> 
Have you tried to compile the code ? 
> 

Hello,
got it now and tried it with that result : 
  fatal error: websocket_server.h: No such file or directory
   33 | #include "websocket_server.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
